// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

const _Type_name = "IDENTSTRINGHEREDOCINTEGERFLOATBOOLSTATEMENTADDSUBSTARSLASHPERCENTPOWEREQUALNOTEQUALGTLTGTELTEANDORLPARENRPARENLBRACKETRBRACKETLBRACERBRACECOMMAPERIODQUOTEASSIGNEOFINVALID"

var _Type_index = [...]uint8{0, 5, 11, 18, 25, 30, 34, 43, 46, 49, 53, 58, 65, 70, 75, 83, 85, 87, 90, 93, 96, 98, 104, 110, 118, 126, 132, 138, 143, 149, 154, 160, 163, 170}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
