name = "jenkins_error"

triggers {
	type = "webhook"
	options {
		method = "POST"
		type = "application/json"
	}
}

steps [
	{
		layer = "kv"
		statements [
			q = `get {trigger.name}`
		]
		export [
			q
		]
	}
	{q} != nil && {trigger.build.status} == "SUCCESS" {
		layer = "trello"
		statements [
			`delete_card ${q.card_id}`
		]
	}
	{q} == nil && {trigger.build.status} != "SUCCESS" {
		layer = "trello"
		statements [
			card = `create_card {trigger.name} xxxx`
		]
		export [
			card
		]
	}
	{card} != nil {
		layer = "kv"
		statements [
			`pus {trigger.name} card`
		]
	}
]

hooks [
	on_error {
		layer = "trello"
	  	statements [
			`create_card {q.card_id}`
		]
	}
]

layers [
	trello {
		source = "git://github.com/NieR/nier-trello@v1.0.0"
		options {
			xxx = {secrets.trello_api_key}
			yyy = "yyy"
		}
	}
	kv {
		options {
			type = "persistent"
		}
	}
]

variables {
	trello_board_id = "xxx"
	long_string = <<EOF
xxxxxx
xxxxx
xxxx
EOF
}

secrets {
	trello_api_key = "xxx"
}